"""empty message

Revision ID: fdc174dede78
Revises: d9ebe306cc18
Create Date: 2018-01-27 21:59:16.746798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdc174dede78'
down_revision = 'd9ebe306cc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'role',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.alter_column('auth_user', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'status',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.alter_column('auth_user', 'role',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    # ### end Alembic commands ###
